
namespace Armoire.Features.Outfits.Models;

using System;
using System.Collections.Generic;

/// <summary>
/// Represents a saved outfit, containing both the visual state (Glamourer) 
/// and the technical requirements (Penumbra Mods) needed to recreate it perfectly.
/// </summary>
public class ArmoireOutfit {
    /// <summary>
    /// A unique identifier for local storage management.
    /// </summary>
    public Guid Id { get; set; } = Guid.NewGuid();

    /// <summary>
    /// The name of the outfit chosen by the user.
    /// </summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// The Base64 string generated by Glamourer representing the character's equipment and appearance.
    /// </summary>
    public string GlamourerBase64 { get; set; } = string.Empty;

    /// <summary>
    /// The list of mods that must be installed and active for this outfit to display correctly.
    /// </summary>
    public List<OutfitModRequirement> RequiredMods { get; set; } = [];

    /// <summary>
    /// Used to handle future updates. If we change how outfits are saved in 2027, 
    /// this version number will allow Armoire to smoothly migrate old outfit codes.
    /// </summary>
    public int FormatVersion { get; set; } = 1;

    /// <summary>
    /// The date this outfit was created or imported.
    /// </summary>
    public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow;

    /// <summary>
    /// The snapshot of the equipment worn by the character when this outfit was saved.
    /// Used purely for the UI to show the user exactly what is in this outfit.
    /// </summary>
    public List<OutfitEquipmentPiece> Equipment { get; set; } = [];
}